### ISSUE TITLE
Mac OS Compatibility

### ISSUE THREAD

**Issue by LocheBC** [toowaki/AutoFitRowEx#2] opened 2023-01-25 17:54 UTC
Hi there,

Thanks for your work.

Any chance this could be compatible with the Mac OS version of Excel?

I'm currently using Mac OS Ventura 13.2 and Excel 2019.

Cheers

**Comment by toowaki** [comment] 2023-02-12 12:42
Hello LocheBC,

I'm sorry, but I have not confirmed the operation on MacOS. 
Can .xlsm be used with Excel on MacOS?

Best regards,
toowaki

**Comment by toowaki** [comment] 2023-02-27 20:24
I'd like to support Mac, but I can't because I don't have a development environment.  Therefore, I will close this issue.

**Closed as completed by toowaki** 2023-02-27 20:24 UTC
